#!/bin/sh
#PBS -N <> 
#PBS -l nodes=1:ppn=28
#PBS -l walltime=5:0:0

#PBS -q cu 

cd $PBS_O_WORKDIR
#module remove anaconda/2
#module add anaconda/3
#export MKL_NUM_THREADS=1
#export MPLBACKEND='AGG'
#module add gcc
#module add matlab

